@startuml Components_Diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Диаграмма компонентов: Интернет-банк (модуль депозитов)

Container(интернет_банк, "Интернет-банк", "ASP.NET MVC")

Component(депозитный_ui, "UI депозитов", "React.js", "Форма открытия депозита")
Component(api_ставок, "API ставок", ".NET Core", "Кэширование и логика ставок")
Component(баланс_клиента, "API баланса", ".NET Core", "Проверка баланса счета")
Component(sms_сервис, "SMS-сервис", ".NET Core", "Интеграция с шлюзом")

Rel(депозитный_ui, api_ставок, "Запрос ставок", "REST")
Rel(депозитный_ui, баланс_клиента, "Проверка баланса", "REST")
Rel(депозитный_ui, sms_сервис, "Подтверждение операции", "REST")
Rel(api_ставок, абс, "Синхронизация ставок", "API Gateway")

@enduml