@startuml Context_Diagram_v2
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Контекстная диаграмма: Микросервис депозитов

Person(клиент, "Клиент")
System(интернет_банк, "Интернет-банк", "Прием заявок")
System(микросервис, "Микросервис депозитов", ".NET 6 + MS SQL")
System(абс, "АБС", "Oracle PL/SQL")
System(очередь, "RabbitMQ", "Очередь сообщений")
System(смс_шлюз, "СМС-шлюз")

Rel(клиент, интернет_банк, "Подает заявку", "HTTPS")
Rel(интернет_банк, очередь, "Отправляет заявку", "AMQP")
Rel(очередь, микросервис, "Читает заявку", "AMQP")
Rel(микросервис, смс_шлюз, "Отправка SMS", "SOAP")
Rel(абс, очередь, "Публикует ставки", "AMQP")
@enduml

