@startuml Context_Diagram_Stavki
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Контекстная диаграмма: Передача ставок в кол-центры

Person(оператор, "Оператор кол-центра", "Консультирует клиентов по ставкам.")
System(абс, "АБС", "Хранит и рассчитывает ставки по депозитам.")
System(крм, "CRM кол-центра", "Отображает ставки оператору.")
System(sftp, "SFTP-сервер", "Хранит файлы с ставками для партнера.")
System(партнер, "Партнерский кол-центр", "Внешняя система, получает ставки через файлы.")

Rel(абс, sftp, "Ежедневно выгружает CSV-файл", "SFTP (PGP)")
Rel(абс, крм, "Предоставляет ставки через API", "REST")
Rel(крм, оператор, "Отображает ставки", "Web-интерфейс")
Rel(sftp, партнер, "Забирает файл", "SFTP")

@enduml